const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.jumpthru,
		C3.Behaviors.bound,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Button,
		C3.Plugins.Mouse,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnFall,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Browser.Acts.Close
	];
};
self.C3_JsPropNameTable = [
	{vida: 0},
	{podeLevarDano: 0},
	{Invencível: 0},
	{lento: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{PularAtravés: 0},
	{RestritoAoLayout: 0},
	{Piscar: 0},
	{Player: 0},
	{Teclado: 0},
	{X_Anterior: 0},
	{Senóide: 0},
	{Lobo: 0},
	{Áudio: 0},
	{morte_chão: 0},
	{Sólido: 0},
	{bloco1: 0},
	{bloco2: 0},
	{bloco3: 0},
	{bloco6: 0},
	{bloco4: 0},
	{bloco5: 0},
	{bloco8: 0},
	{bloco7: 0},
	{bloco9: 0},
	{bloco10: 0},
	{bloco12: 0},
	{bloco13: 0},
	{bloco11: 0},
	{bloco14: 0},
	{bloco15: 0},
	{bloco16: 0},
	{bloco17: 0},
	{bloco18: 0},
	{bloco19: 0},
	{Projétil: 0},
	{aranha: 0},
	{bloco20: 0},
	{bloco22: 0},
	{bloco21: 0},
	{bloco23: 0},
	{bloco24: 0},
	{bloco25: 0},
	{bloco26: 0},
	{bloco27: 0},
	{bloco28: 0},
	{Estrela: 0},
	{bloco29: 0},
	{bloco30: 0},
	{bloco31: 0},
	{bloco32: 0},
	{bloco33: 0},
	{teiaDeAranha: 0},
	{GameOver: 0},
	{Txt_Contador: 0},
	{Senóide2: 0},
	{fantasma1: 0},
	{bloco34: 0},
	{bloco35: 0},
	{bloco36: 0},
	{bloco37: 0},
	{bloco39: 0},
	{bloco38: 0},
	{bloco40: 0},
	{bloco43: 0},
	{bloco44: 0},
	{bloco42: 0},
	{bloco45: 0},
	{bloco41: 0},
	{bloco46: 0},
	{bloco47: 0},
	{bloco48: 0},
	{bloco49: 0},
	{bloco50: 0},
	{bloco51: 0},
	{fantasma2: 0},
	{CASA: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Âncora: 0},
	{coração: 0},
	{vida5: 0},
	{capaDoJogo: 0},
	{gameOverok: 0},
	{PLAY: 0},
	{Mouse: 0},
	{telaPreta: 0},
	{REINICIAR: 0},
	{pontuação: 0},
	{telaDeYouWin: 0},
	{RECOMEÇE: 0},
	{SAIR: 0},
	{começar: 0},
	{Navegador: 0},
	{LEAVE: 0},
	{lanterna: 0},
	{Morreu: 0},
	{Score: 0},
	{pontos: 0},
	{Vida: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Lobo: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	morte_chão: class extends self.ISpriteInstance {},
	bloco1: class extends self.ISpriteInstance {},
	bloco2: class extends self.ISpriteInstance {},
	bloco3: class extends self.ISpriteInstance {},
	bloco6: class extends self.ISpriteInstance {},
	bloco4: class extends self.ISpriteInstance {},
	bloco5: class extends self.ISpriteInstance {},
	bloco8: class extends self.ISpriteInstance {},
	bloco7: class extends self.ISpriteInstance {},
	bloco9: class extends self.ISpriteInstance {},
	bloco10: class extends self.ISpriteInstance {},
	bloco12: class extends self.ISpriteInstance {},
	bloco13: class extends self.ISpriteInstance {},
	bloco11: class extends self.ISpriteInstance {},
	bloco14: class extends self.ISpriteInstance {},
	bloco15: class extends self.ISpriteInstance {},
	bloco16: class extends self.ISpriteInstance {},
	bloco17: class extends self.ISpriteInstance {},
	bloco18: class extends self.ISpriteInstance {},
	bloco19: class extends self.ISpriteInstance {},
	aranha: class extends self.ISpriteInstance {},
	bloco20: class extends self.ISpriteInstance {},
	bloco22: class extends self.ISpriteInstance {},
	bloco21: class extends self.ISpriteInstance {},
	bloco23: class extends self.ISpriteInstance {},
	bloco24: class extends self.ISpriteInstance {},
	bloco25: class extends self.ISpriteInstance {},
	bloco26: class extends self.ISpriteInstance {},
	bloco27: class extends self.ISpriteInstance {},
	bloco28: class extends self.ISpriteInstance {},
	Estrela: class extends self.ISpriteInstance {},
	bloco29: class extends self.ISpriteInstance {},
	bloco30: class extends self.ISpriteInstance {},
	bloco31: class extends self.ISpriteInstance {},
	bloco32: class extends self.ISpriteInstance {},
	bloco33: class extends self.ISpriteInstance {},
	teiaDeAranha: class extends self.ISpriteInstance {},
	GameOver: class extends self.ITextInstance {},
	Txt_Contador: class extends self.ITextInstance {},
	fantasma1: class extends self.ISpriteInstance {},
	bloco34: class extends self.ISpriteInstance {},
	bloco35: class extends self.ISpriteInstance {},
	bloco36: class extends self.ISpriteInstance {},
	bloco37: class extends self.ISpriteInstance {},
	bloco39: class extends self.ISpriteInstance {},
	bloco38: class extends self.ISpriteInstance {},
	bloco40: class extends self.ISpriteInstance {},
	bloco43: class extends self.ISpriteInstance {},
	bloco44: class extends self.ISpriteInstance {},
	bloco42: class extends self.ISpriteInstance {},
	bloco45: class extends self.ISpriteInstance {},
	bloco41: class extends self.ISpriteInstance {},
	bloco46: class extends self.ISpriteInstance {},
	bloco47: class extends self.ISpriteInstance {},
	bloco48: class extends self.ISpriteInstance {},
	bloco49: class extends self.ISpriteInstance {},
	bloco50: class extends self.ISpriteInstance {},
	bloco51: class extends self.ISpriteInstance {},
	fantasma2: class extends self.ISpriteInstance {},
	CASA: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	coração: class extends self.ISpriteInstance {},
	vida5: class extends self.ITextInstance {},
	capaDoJogo: class extends self.ISpriteInstance {},
	gameOverok: class extends self.ITextInstance {},
	PLAY: class extends self.IButtonInstance {},
	Mouse: class extends self.IInstance {},
	telaPreta: class extends self.ISpriteInstance {},
	REINICIAR: class extends self.IButtonInstance {},
	pontuação: class extends self.ITextInstance {},
	telaDeYouWin: class extends self.ISpriteInstance {},
	RECOMEÇE: class extends self.IButtonInstance {},
	SAIR: class extends self.IButtonInstance {},
	começar: class extends self.ITextInstance {},
	Navegador: class extends self.IInstance {},
	LEAVE: class extends self.IButtonInstance {},
	lanterna: class extends self.ISpriteInstance {}
}